name: nf-workflows
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mafft=7.475
  - t_coffee=11.0.8
  - muscle=3.8.1551
  - clustalo=1.2.4
  - gblocks=0.91b
  - parallel=20201122
  - hyphy=2.5.25
  - blast=2.11.0
  - hmmer=3.3.2
  - gffread=0.12.1
  - cd-hit=4.8.1
  - transdecoder=5.5.0
  
